@startuml

interface RedisCommand {
    Object[] components
}

interface KeyedRedisCommand extends RedisCommand {
    Object[] getKeys()
}

class RedisClient implements RedisMessageConsumer {
    Stream<String> scan()
}

interface RedisMessageConsumer {
    void consumeMessage(Channel, Object)
    void handleChannelClosure(Channel)
}

interface RedisCommandExecutor {
    CompletableFuture<Object> executeCommand(RedisCommand)
}

RedisChannel o-- RedisMessageConsumer
RedisClient o-- RedisChannel

@enduml